### ISSUE TITLE
Chef Client Run Error -  undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by gryte** [gryte/dockerserver#5]
## Expected Behavior

The chef-client run should complete without error.

## Current Behavior

The chef-client run started to fail with the following stack trace:
```bash
/var/chef/cache/cookbooks/dockerserver/recipes/default.rb:51:in `block in from_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/resource_builder.rb:66:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/resource_builder.rb:66:in `build'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/dsl/declare_resource.rb:314:in `build_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/dsl/declare_resource.rb:271:in `declare_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/dsl/resources.rb:38:in `remote_file'
/var/chef/cache/cookbooks/dockerserver/recipes/default.rb:50:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/cookbook_version.rb:199:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/run_context.rb:350:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/run_context/cookbook_compiler.rb:166:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/run_context/cookbook_compiler.rb:163:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/run_context/cookbook_compiler.rb:163:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/run_context/cookbook_compiler.rb:79:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/run_context.rb:199:in `load'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/client.rb:512:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/client.rb:278:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application.rb:321:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application.rb:309:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application.rb:309:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application.rb:274:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application/client.rb:476:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application/client.rb:465:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application/client.rb:464:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application/client.rb:464:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application/client.rb:448:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:71:in `load'
/usr/bin/chef-client:71:in `<main>'
```

## Possible Solution

It looks like the `remote_file` resource that installs the docker-compose binary may no longer be referencing the correct url. This url is being built with some node attributes based on the OS and architecture so the first step is to confirm the expected url location along with the node attributes.

## Steps to Reproduce (for bugs)

1. The chef-client run is scheduled on a 30 minute frequency with a 5 minute splay, so it's just a matter of reading the error log on the node or in the manage ui console *(run chef-client)*

## Context

Current impact to existing infrastructure is negligible *(my docker host and containers are running just fine)*.

Recent changes were introduced to allow a chef handler cookbook send updates to slack which included revisiting role layouts. None of this should have impacted this server and in fact the client runs were successful for some time. This may be an opportunity to update the version of docker-compose to install since I'm pretty far back in the versions. 

I'm trying to ensure the chef-client runs are successful again.

## Your Environment

* Version used: `dockerserver cookbook 1.3.3, chef-client version 14.1.1`
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): `docker-compose 1.14.0`
* Server type and version: `Proxmox Virtual Environment 4.4-15/7599e35a`
* Operating System and version: `centos 7`
* Link to your project: https://github.com/gryte/dockerserver

**Comment by gryte** [comment]
Huh, it would appear that the node attribute I was successfully using before now returns an error...

```bash
[root@dockerserver ~]# chef-shell
loading configuration: none (standalone session)
Session type: standalone
Loading...done.

This is the chef-shell.
 Chef Version: 14.1.1
 https://www.chef.io/
 https://docs.chef.io/

run `help' for help, `exit' or ^D to quit.

Ohai2u alinkous@dockerserver.linkous!
chef (14.1.1)> puts node['packages']['kernel']['arch']
Traceback (most recent call last):
        7: from /bin/chef-shell:71:in `<main>'
        6: from /bin/chef-shell:71:in `load'
        5: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/bin/chef-shell:36:in `<top (required)>'
        4: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/shell.rb:80:in `start'
        3: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/shell.rb:80:in `catch'
        2: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/shell.rb:81:in `block in start'
        1: from (irb):1
NoMethodError (undefined method `[]' for nil:NilClass)
chef (14.1.1)> puts node['os']
linux
 => nil
chef (14.1.1)> puts node['packages']['kernel']

 => nil
chef (14.1.1)> puts node['packages']
{}
 => nil
chef (14.1.1)>
```

**Comment by gryte** [comment]
Looking through ohai and it appears that I should use a different set of attributes:

```bash
...
 },
 "kernel": {
   "name": "Linux",
   "release": "3.10.0-693.11.6.el7.x86_64",
   "version": "#1 SMP Thu Jan 4 01:06:37 UTC 2018",
   "machine": "x86_64",
...
```

**Comment by gryte** [comment]
I'm going to try these instead:

```bash
[root@dockerserver ~]# chef-shell
loading configuration: none (standalone session)
Session type: standalone
Loading....done.

This is the chef-shell.
 Chef Version: 14.1.1
 https://www.chef.io/
 https://docs.chef.io/

run `help' for help, `exit' or ^D to quit.

Ohai2u alinkous@dockerserver.linkous!
chef (14.1.1)> puts node['kernel']['name']
Linux
 => nil
chef (14.1.1)> puts node['kernel']['machine']
x86_64
 => nil
chef (14.1.1)>
```

**Comment by gryte** [comment]
Even after implementing all that, I ran into the issue of the firewalld resource failing on the `Thread died in Berkeley DB library` issue. Most likely the root cause of this issue was a corrupted rpm db. This was resolved by following the following steps per [Fix rpmdb: Thread died in Berkeley DB library](https://cloudlinux.zendesk.com/hc/en-us/articles/115004075294-Fix-rpmdb-Thread-died-in-Berkeley-DB-library):

```bash
# mkdir /var/lib/rpm/backup
# cp -a /var/lib/rpm/__db* /var/lib/rpm/backup/
# rm -f /var/lib/rpm/__db.[0-9][0-9]*
# rpm --quiet -qa
# rpm --rebuilddb
# yum clean all
```

Eh, at least I updated the cookbook to be a bit more flexible and use a later version of docker-compose. :)
